- src/naemon/checks.c
- src/naemon/commands.c
- src/naemon/commands.h
- src/naemon/configuration.c
- src/naemon/events.c
- src/naemon/naemon.c
- src/naemon/naemon.h
- src/naemon/nerd.c
- src/naemon/notifications.c
- src/naemon/notifications.h
- src/naemon/query-handler.c
- src/naemon/shadownaemon.c
- src/naemon/utils.c
- src/naemon/xodtemplate.c
Signed-off-by: Emil Hessman <emil@hessman.se>
> naemon: fix typos

- src/shadownaemon/shadownaemon.c
- src/shadownaemon/shadownaemon.h
shadownaemon updates. Use fixed dummy command instead of the first one and change to iobroker based event poll since that is required for livestatus now.
> Shadownaemon iobroker

- src/naemon/commands.c
> fix typo in commands.c

- src/naemon/commands.c
> external command CHANGE_SVC_MODATTR does not work

- src/naemon/commands.c
> fix external command CHANGE_SVC_MODATTR

- ChangeLog
- NEWS
An attempt to create a change log for the 1.0.7 release.
Signed-off-by: Jacob Hansen <jhansen@op5.com>
> Added changelog for 1.0.7 release

- autogen.sh
- debian/control
- debian/naemon-core.dsc
- debian/rules
- naemon-core.spec
Some final changes to get osb builds working.
> Fix packaging

- daemon-init.in
Set variables for naemon process (e.g. LANG and LC_ALL) to work around some (plugin threshold) issues
> daemon-init.in: Source "/etc/default/naemon" if exists

- debian/naemon-core.naemon.init
Fixes issue #150 for debian/ubuntu packaging as well.
> Reload : Fix defunct

- src/naemon/checks_host.c
- src/naemon/checks_service.c
the orphaned check eventhandler checks the next_check against the expected next
check. But normal service/host check events simply run schedule_next_... so
then orphan check will never match.
right now its like this:
handle_host_check_event()
->  run_async_host_check()
->  sets is_executing true
->  check never comes back
->  next check scheduled
handle_host_check_event()
->  run_async_host_check()
->  returns an error because is_executing is still set
->  next check scheduled
So since next_check is always pushed forward, the orphan check will never
match, even if the host/service has the is_executing flag for days. To fix
this, we only reschedule the next check if the is_executing flag is false.
Now when the check takes longer than the check interval, this can lead to
situations that …
> fix orphaned checks logic

- NEWS
- debian/changelog
- naemon-core.spec
- version.sh
> release 1.0.10

- src/naemon/commands.c
> add missing documentation

- NEWS
- debian/changelog
- naemon-core.spec
- version.sh
> release 1.1.0

- src/naemon/objects_timeperiod.c
> Fix sprintf format error with clang

- src/naemon/objects_timeperiod.c
> Change timerange2str to use short instead of int

- NEWS
- debian/changelog
- naemon-core.spec
- version.sh
* Add new skip check options to set a particular state on skipped checks
* Retain flap detection option over restarts
* Don't process perfdata file if perfdata is disabled
> release 1.2.0

- Makefile.am
- NEWS
- debian/changelog
- naemon-core.spec
- version.sh
Changed:
* nothing
Bugfixes:
* fix executing commands with pipes (#319)
* fix external command to remove downtimes by filter
> Release 1 2 1

- Makefile.am
- debian/changelog
fixing copy&paste error. This is the core pkg.
> fix typo in release files

- .travis.yml
I have no particular need for these emails any longer.
> Remove my email from travis config

- NEWS
- debian/changelog
- naemon-core.spec
- version.sh
1.2.2 - Nov 13 2020
===================
Features:
* none
Changed:
* improved sample configuration
* improved external command help
* debian package source format changed
* debian packages changed to systemd
Bugfixes:
* fix scheduling flexible service downtime
* fix setting last_update whenever next_check changes
* fix worker crashing
> release 1.2.2

- .travis.yml
- features/environment.py
- features/steps/naemon.py
- features/support/naemon_system_config.py
Elevate behave feature tests to Python 3 compatible code and install/run
Python 3 in Travis CI.
Signed-off-by: Aksel Sjögren <asjogren@itrsgroup.com>
> Run behave feature tests with Python 3

- NEWS
- debian/changelog
- naemon-core.spec
- version.sh
Features:
* improve config check when having lots of servicegroups
Changed:
* migrate ci tests to github actions
* change header file location in deb/rpm packages
Bugfixes:
* fix svc in check_command broker call
> release 1.2.4

- NEWS
- debian/changelog
- naemon-core.spec
- version.sh
1.3.0 - Nov 03 2021
===================
Features:
* new vault broker api
* secure environment variables
Changed:
* none
Bugfixes:
* none
> release 1.3.0

- README.md
Add a badge for the Github CI actions result to the README
> README.md: Add Github Workflow badge

- debian/control
- debian/libnaemon.install
- debian/naemon-core.install
- debian/naemon-core.links
- debian/naemon-core.lintian-overrides
- debian/naemon-dev.install
- debian/rules
My take on https://github.com/naemon/naemon-core/pull/389
> Multiarch build for Debian/Ubuntu

- README.md
The README was a bit misleading. This commit should make the instructions easier to follow on more relevant.
> README: Update install/compile instructions

- src/naemon/common.h
- src/naemon/naemon.h
> cleanup some unused macros

- daemon-init.in
- replace `==` with `=`
- replace `type` with `command -v` (see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=747320 for a discussion)
> fix bashisms (fixes #406)

- daemon-systemd.in
- naemon-core.spec
- naemon.tmpfiles.conf
This is my attempt to patch #409 . Please verify my changes.
Signed-off-by: midnight-run 1+dasgithub@kmdinata.ch
> fix systemd configuration from using legacy directory and apply systemd-tmpfiles settings

- NEWS
- debian/changelog
- naemon-core.spec
- version.sh
> release 1.4.1

- naemon-core.spec
- Add conditionals for EL9 support.
- Use the pre-defined `optflags` variable to set the CFLAGS.
> Support el9

- README.md
The github actions status badge is not working. This pr will fix it.
> Fix GitHub actions status badge
