- src/naemon/xodtemplate.c
Noticed the error while using naemon; not a complete review of comments/code
> Minor spelling error, hostgrop -> hostgroup

- src/shadownaemon/shadownaemon.c
Set last_state, last_hard_state, last_hard_state_change explicitly.
For example Nagvis needs last_hard_state when only_hard_states is
set. When not propagated, Nagvis shows always OK for hosts and
services queried over shadownaemon.
> shadownaemon: propagate last_hard_* values

- daemon-init.in
On CentOS 6, doing service reloads when having broken object configuration will kill the main naemon process.  Added check_config to the reload command will prevent the reload from happening and show that the current configuration is invalid.
> Updated daemon-init.in to protect reloads from killing the daemon

- src/naemon/checks.c
Prevent Naemon from segfaulting when a plugin's
output is one or more newlines only.
> Fix segfault issue on newline output from plugin

- src/shadownaemon/shadownaemon.c
Since the removal of external commands, shadownaemon was
using the incorrect request index when updating last_request_count.
Consequently, the poll interval was decided based on wrong values.
> shadownaemon: use correct request index

- src/shadownaemon/shadownaemon.c
If there have been requests while using the long poll
interval, shadownaemon no longer sleeps for the remainder
of the long interval before returning to the main refresh loop.
> shadownaemon: faster return to short poll interval

- lib/worker.c
- lib/worker.h
- src/naemon/commands.c
- src/naemon/query-handler.c
- src/naemon/workers.c
- src/worker/worker.c
In particular, don't assume it is an unsigned long, because on i386 (for
instance), it's not.
Signed-off-by: Anton Lofgren <alofgren@op5.com>
> Don't make assumptions about size_t

- .gitignore
- version.sh
Right now, the -source appendix is hard coded in the version script,
so add a way to flag official builds by an empty file.
Signed-off-by: Sven Nierlein <Sven.Nierlein@consol.de>
> make it possible to build official packages

- sample-config/naemon.cfg.in
new installations should not come with warnings like:
Warning: enable_environment_macros is deprecated and will be removed.
> remove enable_environment_macros from sample config

- version.sh
In some build systems, git is not present unless defined as a build
dependency. However the .git directory may still be copied in along with
the source. This change will still allow the required behavior in case
.git is present but the Git binary is not.
> Checking for Git binary

- src/naemon/notifications.c
broker_notification_data returns a neb_resultset which needs to be freed, even if we
don't use it.
> fix memory leak in broker_notification_data

- src/naemon/commands.c
If a worker exits because the main naemon process has exited it writes
one last log entry. This entry is likely to end up in an already rotated
old logfile which breaks livestatus.
It then exits with EXIT_SUCCESS, so its not really an error anyway and
therefor we can just lower the loglevel.
> lower loglevel for exiting worker

- src/naemon/xrddefault.c
This fix is not Naemon specific, it is also applicable to Nagios.
> xrddefault: Fix custom variables persistence accros restarts

- daemon-systemd.in
Precached objects file was created before but never used. So there is no need to create it.
> systemd: do not use precached objects

- src/naemon/naemon.c
Even though running as root is not recommended, there are cases where running
as root facilitates things a lot. An example could be a test environment and
another a Docker container.
Signed-off-by: Tomas Vestelind <tvestelind@op5.com>
> allow running as root if --allow-root flag is given

- daemon-systemd.in
from man systemd.service "For each of the specified commands, the first argument must be an absolute path to an executable."
> systemd requires absolute path in execstart

- daemon-systemd.in
NICELEVEL is not set by default, so systemd constantly complains about the value not beeing set.
> remove NICELEVEL from systemd service

- daemon-init.in
- daemon-systemd.in
- op5build/naemon.service.in
In a large setup where it can take more than 30 seconds to verify a config.
I propose a implementation similar to other systems, like Apache httpd.
* If you change your config and restart Apache httpd, the server won't start
and you have a broken config. (Expected)
* If you run a verify on the config, it will verify without interrupt with
your current running instance.
But doing this we can speed up the actual start/stop/restart of the naemon
process.
Signed-off-by: Mattias Ryrlén <mattiasr@op5.com>
> Minimize the amount of verify-config

- src/naemon/checks_host.c
- src/naemon/checks_service.c
- src/naemon/workers.c
- tests/test-worker.c
Do not log timeouts 3 times for each timeout. Timeouts are a normal thing in
monitoring and state changes are logged already, there is no need to add 2
extra log entries, one from wproc and one from the check handler. Especially since
the timeout is quite visible already and the extra logging does not add any value.
> reduce log spam

- features/environment.py
- features/steps/naemon.py
- op5build/ci_config.yml
Added ability to omit setting the executable path to the
naemon binary and the shared libraries. Also added possibility
to use absolute paths.
Signed-off-by: Robin Engström <robin.engstrom@op5.com>
> naemon executable path

- src/naemon/configuration.c
Reading check results from disk is not a bad thing. Lot of addons use this for good reasons.
Ex. Thruk submits business process results by spool folder. We could make check_result_path
optional, but i don't recommend removing it. Therefor we remove the deprecation warning.
> undeprecate check_result_path

- src/naemon/nebmods.c
nebcallback resultset may be null if eventbroker options prevent
notifications from beeing brokered. Do not segfault in those
cases.
> fix segfault in notifications when there is no eventbroker

- src/naemon/macros.c
The DATE / TIME macros were not freeing the allocated pointer.
I had to swap mkstr for asprintf in order to be able to free the pointer outside the function.
> Fixes memory leak for DATE/TIME Macros

- src/naemon/downtime.c
- src/naemon/downtime.h
- src/naemon/xrddefault.c
- tests/test-scheduled-downtimes.c
Comments related to downtimes are beeing added with persistance=false flag. This
leads to the comment beeing removed during a reload. The downtime then immediatly
adds the comment again but the id increments each reload. Furter this results in
a warning from livestatus for each downtime on every reload:
livestatus: Cannot delete non-existing downtime/comment
> fix comment ids increment on reload

- src/naemon/checks.c
- src/naemon/xrddefault.c
- tests/test-checks.c
- tests/test-retention.c
parse_check_outputs() escape_newlines_please argument has been ignored but it
is explicitly requested from the worker.  This leads to issues in csv output of
livestatus, since livestatus assumes the longout put to be escaped while it was
not. So it returned newlines just as is instead of escaped ones.
> fix newline escaping for check results

- src/naemon/perfdata.c
We need to check the service_perfdata_fd/host_perfdata_fd as well when pushing
performance data onto our buffer. Checking the template does not work because
it is never NULL as it will be set to a default if its unset.
This should fix issue #200.
> fix memory leak when collecting performance data

- lib/runcmd.c
- lib/snprintf.c
- src/naemon/checks.c
- src/naemon/configuration.c
- src/naemon/macros.c
- src/naemon/xodtemplate.c
GCC 7 introduced new warnings which, as we compile Naemon with -Werror, meant that the builds failed.
The warnings are trigged when building naemon are:
-Wimplicit-fallthrough which warns if there are any fallthroughs in switch/case statements.
-Wformat-truncation which warns if output from a formatting operating could be truncated (for example when running snprintf)
These two patches ensures that Naemon can be correctly built with GCC 7. See the individual commit messages for further information.
This should fix #184
> Allow compilation with GCC 7

- src/naemon/checks_service.c
Adding a log message to explain why the hard states switching happened.
Signed-off-by: Nian Tang <ntang@op5.com>
> Logging for switching service states for host down 

- naemon-core.spec
This file has been listed twice, under naemon-core and libnaemon. It should be listed only once.
> rpm: remove duplicate listing of naemonstats manpage

- debian/changelog
- naemon-core.spec
bump versions in the spec file and the debian changelog as well. Otherwise the release packages would have the old version. Only daily builds get increased automatically.
> bump version in spec and debian files

- naemon-core.spec
naemon-tools are now part of the naemon-core project. Adding an obsoletes should
make updates smoother.
> add obsoletes for naemon-tools

- src/naemon/checks_host.c
- src/naemon/checks_service.c
- src/naemon/commands.c
- src/naemon/notifications.c
- src/naemon/perfdata.c
- src/naemon/workers.c
newlines are not automatically added and must be manually appended to each log entry.
> add missing newlines to log_debug_info (fixes #247)

- naemon-core.spec
Resolves upgrade issues when updating from 1.0.6 to 1.0.8.
Upgrading from Naemon 1.0.6 / 1.0.7 on CentOS 7 may, depending on the order yum decides to install packages, fail with:
`file /usr/share/man/man8/naemonstats.8 from install of naemon-core-1.0.8-0.x86_64 conflicts with file from package libnaemon-1.0.6-1.el7.centos.x86_64`
This lets naemon-core depend on libnaemon, ensuring updating always takes place in the correct order.
Fixes #249.
> Make naemon-core depend on libnaemon

- src/naemon/checks_service.c
- tests/test-check-scheduling.c
The current [Naemon documentation](https://www.naemon.org/documentation/usersguide/hostchecks.html#when_are_host_checks_performed) states that on-demand host checks are performed when a service associated with the host changes state. This is not actually what happens. Currently on-demand host checks are scheduled on any service checks which results in a non-ok state for the service (even if there is no state change)
This commit changes that logic slightly, so that on-demand host checks are performed when the service changes state OR if the service is in a soft state. That is, we no longer do on-demand host checks on non-ok service checks, if the service is already in hard critical.
This ensures that we do not do a high amount of host checks when a host and all its services are in hard …
> No on-demand host check on service hard critical

- src/naemon/checks.c
- tests/test-checks.c
This patch ensures that newlines which are already escaped in a check results long_output is not escaped again.
When running [Merlin](https://github.com/op5/merlin) to have a distributed Naemon setup, we had a problem where a check result coming from another node, would have double escaped new lines. Merlin sends check results to different nodes, after the check_result has been parsed. The receiving node would in turn also run it through Naemons check result parsing mechanism. This resulted in newlines being escaped twice, once on the remote node, and once on the master (for example). 
This fix works by adding "\\n" to the exception list of g_strescape, which means already escaped newlines won't be escaped again.
This fixes [MON-11112](https://jira.op5.com/browse/MON-11112)
> parse_check: Don't escape already escaped newlines

- src/naemon/checks_host.c
- src/naemon/checks_service.c
- tests/test-check-scheduling.c
This commit ensures that the next_check schedule for hosts and services
are retained on Naemon restart, given that use_retained_scheduling_info
is enabled.
The logic is as follows:
- If use_retained_scheduling_info is disabled, set a random time (as
before)
- If use_retained_schedule_info is enabled:
- If we didn't miss the check during the restart, retain the old
next_check time
- If we missed one check, schedule the service/host within the next
interval_length (usually 60 seconds)
- If we missed more than one check, schedule the next check randomly.
We schedule missed checks within 60 seconds, rather than immediately in
order to do some load balacing. This is also the rationale for
scheduling the check randomly, in case we missed more than one check
(this indicates Naemon has been down …
> Retain next_check schedule on restart (#224, #156)

- naemon-core.spec
Since we install the el7 logrotate in our Makefile.am without further OS
detection we need to replace the logrotate file for el6 later. Otherwise we
would end up with the el7 file and no logrotation.
> el6: use correct logrotate script

- src/naemon/checks_host.c
- src/naemon/checks_service.c
- tests.mk
- tests/test-check-dependencies.c
right now we did only check the state during dependency checks. But for pending hosts
and services the state is usually OK/UP so the check passed. For pending flag checks
we have to look at the has_been_checked flag as well. This leads to the situation where
services checks will be run if the master service is in pending state even if the service
has pending service execution failure flag set.
> fix pending dependencies

- daemon-init.in
- features/daemonize.feature
- features/logging.feature
- features/steps/naemon.py
- src/naemon/sretention.c
When using killproc to kill a process, first a SIGTERM signal is sent, and after a default of 3 seconds (5 seconds on SUSE), a SIGKILL is sent.
On larger setups we often see that 3 seconds, is not sufficient for Naemon to shutdown, and as a result retention data might not be correctly saved.
This commit increase the timeout to 90 seconds on redhat based releases and on SUSE. We only change this one these systems, as killproc seems to differ between different distributions, and might not offer the same arguments. 90 seconds timeout is the default for systemd, and the therefore the rational for choosing that value.
In addition added a log message on save of retention data at shutdown to aid debugging.
More context: [MON-10565](https://jira.op5.com/browse/MON-10565).
> Init: Increase delay between SIGTERM and SIGKILL

- COPYING
Commit: https://github.com/naemon/naemon-core/commit/88e3b60e7bd82171776bda70d3f874e876958daa removed the COPYING file that contained the license for the Naemon project.
The rationale given for this, was that this is auto-generated anyway, so there is no reason to have it in the git repository. I think that it is bad practice to not include a license with a project (even if it should be auto-generated), especially on GitHub, where licenses for projects are detected. 
Furthermore the auto-generated COPYING file, uses GPLv3 while the the rest of the project references to GPLv2 as the license.
I therefore propose that we re-add the COPYING file with the license to the project again.
Automake requires a COPYING file, so we use that rather than LICENSE.
> Re-add COPYING file with license

- src/naemon/checks_host.c
- src/naemon/checks_service.c
- src/naemon/common.h
this flag was used by mod-gearman to detect orphaned checks for example
from misconfiguration to submit a critical check result with a useful
message.
> set flag if check is scheduled from the orphan event handler

- src/naemon/checks_host.c
- src/naemon/checks_service.c
Overriding checks during the host/service_initiate stage leads to a memory leak.
Freeing the check_result pointer helps.
> fix memory leak when overriding checks

- src/naemon/query-handler.c
- tests.mk
- tests/test-query-handler.c
there was a missing newline which prevented the query handler
from returning the errors for commands.
add a test case to ensure this does not fail again.
> fix query handler not returning command response

- src/naemon/nebmods.c
A neb callback deregistering itself in a callback currently causes a heap
corruption. This is due to getting the naming information for the module
after the callback has been run.
This patch gets the naming information of the module before the
callback, ensuring that we will not try to access the callback pointer
after it is potentially freed.
This fixes: MON-11365 & https://github.com/naemon/naemon-core/issues/268
Signed-off-by: Jacob Hansen <jhansen@op5.com>
> Fix heap corruption when callback dereigsters itself

- sample-config/naemon.cfg.in
- src/naemon/checks_host.c
- src/naemon/checks_service.c
- src/naemon/configuration.c
- src/naemon/defaults.h
- src/naemon/globals.h
- src/naemon/utils.c
- tests/test-check-scheduling.c
With use_retained_scheduling_info enabled, we would schedule checks
which was missed with less than one check_interval, within one
interval_lenght.
This commit introduces a new setting
retained_scheduling_randomize_window which allows users to configure
the window in which checks that were missed over a restart is rescheduled.
This can be useful in order to increase the load balacing done after a
restart, and might be able to help fixing CPU load spikes, due to checks
being unevenly scheduled.
This part of MON-11418
Signed-off-by: Jacob Hansen <jhansen@op5.com>
> Introduce retained_scheduling_randomize_window

- src/naemon/checks_host.c
- src/naemon/checks_service.c
returning NEBERROR_CALLBACKCANCEL  from a NEBTYPE_HOSTCHECK_INITIATE or
NEBTYPE_SERVICECHECK_INITIATE neb callback resulted in naemon running the check
itself. Instead naemon should just skip the check and reschedule it.
> allow NEBERROR_CALLBACKCANCEL from NEBTYPE_*CHECK_INITIATE

- src/naemon/workers.c
> fix format overflow

- src/naemon/nebmods.c
loading a neb module multiple times (with different configuration), even from
different files, leads to unwanted results. For example callbacks always
targeted the first loaded module instead of the one which registered the
callback.
This has worked before already, probably because the default used lt_dlopen
without any flags which uses RTLD_LOCAL in fact.
The only scenarion when RTLD_GLOBAL would make sense would be modules which
rely on each other and i am not aware of any module doing something like that.
> fix loading neb module multiple times

- src/naemon/xodtemplate.c
- src/naemon/xodtemplate.h
before this change, expanding wildcards or regular expressions in service lists
resulted in iterating over all services, even for static hostnames. For example
when expanding same host service dependencies still all services will be
checked.
With this patch, we create a shortlist for each hosts services and use that
if possible. Using a example configuration with 80k same host service dependencies
brings down the configuration parsing duration from 20 seconds down to 0.3 seconds.
> avoid iterating all services when expanding service lists

- src/naemon/checks_host.c
- src/naemon/checks_service.c
- src/naemon/commands.c
- src/naemon/nebmodules.h
- src/naemon/notifications.c
- src/naemon/objects_host.h
- src/naemon/objects_service.h
- src/naemon/xrddefault.c
- src/naemon/xsddefault.c
This PR adds a new attribute last_update to hosts and services. This timestamp
will be updated before and after servicechecks, on notifications and on
external commands. Once this timestamp is accessible via livestatus, it will
make synchronisation (ex. by LMD) easier.
> add last_update timestamp to track host/service changes

- src/naemon/macros.c
- t-tap/test_macros.c
using on demand hostgroup macros like $HOSTSTATEID:hostgroupname:,$"  made naemon crash
> fix segfault in on demand group macros

- tests/test-scheduled-downtimes.c
- tests/test-worker.c
it is unsafe to access the downtimes after they have been removed because this
frees the underlaying memory. This might work sometimes if the memory has not
been reused meanwhile but is undefined behaviour.
The effect of has been asserted indirectly through the affected hosts/service already.
> fix downtime tests

- src/naemon/xodtemplate.c
- tests/test-obj-config-parse.c
- tests/test-scheduled-downtimes.c
- tests/test-worker.c
Configuration validation should bail out if host members cannot be found. Right now it would
print an error but continue. Problem here is that the rest of the list is not parsed, so the
first unknown host cuts off the members list.
Same applies to servicegroup members.
> bail out if members cannot be expaned (fixes #300)

- naemon-core.spec
according to https://spdx.org/licenses/ the official license tag is "GPL-2.0-or-later". Otherwise
rpmlint complains about "E: invalid-license"
> fix E: invalid-license

- naemon-core.spec
creating debug packages requires gdb-add-index which is in package gdb-headless. Results in
```
ERROR: GDB index requested, but no gdb-add-index installed
```
otherwise.
> add build requirement for centos 8

- src/naemon/flapping.c
This commit ensures the flap detection of a host/service is retained
over restarts, when changing the flap detection option using an external
command. This is in line with other options such as passive checks,
notifications etc.
> Retain flap detection option over restarts

- src/naemon/perfdata.c
Currently, even if `process_performance_data` is set to 0, the commands
set by `host/service_perfdata_file_processing_command` are executed.
Often these file processing commands move the current perfdata files to
a spool directory. These files will be empty if
`process_performance_data` is set to 0. Given the files are empty
anyway, it does not make a lot of sense to process the perfdata files.
Furthermore, if no software is cleaning up the empty files from the spool
directory, the system will eventually be flooded with empty files.
This commit fixes the above behaviour by not executing the file
processing commands if performance data processing is disabled.
> Don't process perfdata file if perfdata is disabled

- lib/runcmd.c
using a simple shell script like this runs into timeout when run
by naemon because SIGPIPE is beeing ignored for unknown reasons.
```
random-string()
{
/bin/cat /dev/urandom | /bin/tr -dc 'a-zA-Z0-9' | /bin/fold -w ${1:-32} | /bin/head -n 1
}
echo "OK - rand: $(random-string)"
exit 0
```
using the default signal handling right before we run child commands fixes this.
> fix using pipes in commands (fixes #319)

- src/naemon/downtime.c
Today, even if we fail to add a host or service downtime we still send a
NEB callback. This results in Livestatus adding a downtime which was
never actually added in Naemon.
This commit ensures we only send the NEB callback with
`NEBTYPE_DOWNTIME_ADD` if we succeeded in adding the downtime.
> Downtimes: don't send NEB callback if add failed

- src/naemon/commands.c
uninitialised struct causes dereference to random addresses.
I first thought this was due to supplying too few parameters (Icinga 1 only requires one, the hostgroup), but this command would never work, I think.
> fix crash in DEL_DOWNTIME_BY_HOSTGROUP_NAME

- lib/test-iobroker.c
fixes:
```
lib/test-iobroker.c: In function ‘conn_spam’:
lib/test-iobroker.c:125:18: error: cast between incompatible function types from ‘int (*)(int)’ to ‘void (*)(int)’ [-Werror=cast-function-type]
125 |  signal(SIGALRM, (void (*)(int))sighandler);
|                  ^
lib/test-iobroker.c:126:17: error: cast between incompatible function types from ‘int (*)(int)’ to ‘void (*)(int)’ [-Werror=cast-function-type]
126 |  signal(SIGINT, (void (*)(int))sighandler);
|                 ^
```
> correct signal handler return type

- sample-config/naemon.cfg.in
This directive needs to be last, otherwise custom configuration parameters
in that directory may get reset again by whatever comes after the
include_dir= directive in the naemon.cfg file.
Example: maybe we set use_regexp_matching=1 in module-conf.d/local.cfg.
And indeed, include_dir=module-conf.d will parse and honor this setting,
but then use_regexp_matching=0 is set in naemon.cfg again and our
local settings from module-conf.d are gone :(
> Move include_dir= to the very end of the (sample) configuration file.

- src/worker/worker.c
This commit implements a couple of sanity checks on pointers in the
worker process. This is the result of analyzing core-dumps from a crash.
> Worker: Null pointer sanity check before wlog call

- debian/naemon-core.install
- debian/naemon-core.naemon.service
- debian/naemon-core.naemon.tmpfiles
- debian/rules
debian uses systemd and should therefor use systemd service as well.
Signed-off-by: Sven Nierlein <Sven.Nierlein@consol.de>
> debian: install systemd service

- src/naemon/commands.c
- t-tap/test_commands.c
Fixes the issue that a flexible (fixed=0) service downtime doesn't honor
the "duration" argument, but sets the duration to (end_time -
start_time) just like a fixed downtime.
Add test cases for fixed/flexible host/service downtimes.
Signed-off-by: Aksel Sjögren <asjogren@itrsgroup.com>
> Fix scheduling flexible service downtime

- .travis.yml
With this commit slack notification is posted from travis to `#naemon-travis` at the Openmonitoring slack channel.
The travis CLI tools also reformatted the .travis file slightly - I assume with the "correct" formatting.
> Travis: Add slack notifications

- src/naemon/checks_host.c
- src/naemon/checks_service.c
last_update wasn't updated in some cases when only the next_check advances. For example for
pending and disabled hosts/services.
This patch ensures, that whenever next_check is updated, also last_update is set.
> fix next_check synchronisation

- debian/control
- debian/naemon-core.dsc
- debian/naemon-core.install
- debian/rules
The oldest supported system is ubuntu14.04 on obs right now and even that supports systemd already. So
simply move to systemd completely. Detection of system failed on obs on some systems and the packages
end up with half complete systemd integration.
dh_installinit install service anyway, even if we do not add the other systemd files.
[  144s] dh_installinit --name=naemon
[  144s] 	install -d debian/naemon-core/lib/systemd/system
[  144s] 	install -p -m0644 debian/naemon-core.naemon.service debian/naemon-core/lib/systemd/system/naemon.service
> debian: move to systemd

- debian/rules
- naemon-core.spec
Automake automatically adds a package name suffix to `includedir` so it
should be specified as "/usr/include" not "/usr/include/naemon".
Fixes #299.
> Fix header file location in deb/rpm packages

- debian/control
- debian/naemon-core.dsc
it is obsolete since stretch and removed in debian 11.
> dh-systemd has been merged into debhelper

- features/environment.py
- features/logging.feature
- features/restart.feature
- features/steps/filesystem.py
- features/steps/naemon.py
- features/support/__init__.py
We noticed that logging tests failed when building in a new environment, it seemed to be a timing issue where the test case wants to SIGTERM naemon, but some investigation gave that naemon didn't completely start yet, so its signal handlers weren't installed and thus didn't stop as intended. This is an attempt to improve the timing issue.
* Fix test that failed if Naemon haven't yet started correctly and got
it's signal handlers setup at the stage a test case executes the "When
I stop naemon" step.
Add a step that starts Naemon and wait until it finds a line in the
log file that indicates that it should be ready.
It's not perfect, but it seems to make the test case more stable.
* Close opened files in feature tests.
Signed-off-by: Aksel Sjögren <asjogren@itrsgroup.com>
> Fix stopping Naemon in logging feature test

- src/naemon/checks_service.c
This commit fixes a bug where the `check_command` argument was not
correctly set for the calls to `broker_service_check` with the
`NEBTYPE_SERVICECHECK_PROCESSED` type.
This in turn meant that the `command_` members of the
`nebstruct_service_check_data` struct was never populated.
This is similar to the behaviour for host checks.
Signed-off-by: Jacob Hansen <jhansen@itrsgroup.com>
Co-authored-by: Robert Wikman <rwikman@itrsgroup.com>
> Correclty set svc check_command for broker call

- src/naemon/naemon.c
- src/naemon/objects_service.c
- src/naemon/objects_service.h
- src/naemon/objects_servicegroup.c
- src/naemon/objects_servicegroup.h
- src/naemon/utils.c
- t-tap/test_checks.c
- t-tap/test_downtime.c
- tests/test-check-dependencies.c
- tests/test-check-result-processing.c
- tests/test-check-scheduling.c
- tests/test-neb-callbacks.c
- tests/test-retention.c
- tests/test-scheduled-downtimes.c
while clean up we iterate over all services and each service is removed from
all its servicegroups by iterating over the servicegroup members over and over
to remove each service one by one.
Adding a new flag truncate_lists which can be set on teardown to simply iterate once
over each list and remove/free all items.
This reduces the duration of a config check for an example config with 100k services from
30seconds to less than 3seconds.
> speed up cleanup() when having servicegroups

- lib/runcmd.c
- lib/runcmd.h
- lib/test-runcmd.c
- src/worker/worker.c
This PR removes exposing environment variables to the process list. The
example command line: TEST=1 FOO=BAR /bin/true
would be executed like: /bin/sh -c 'TEST=1 FOO=BAR /bin/true'
and the environement variables would be visible in ps output.
Instead we extend command line parsing and remove environment variable
definitions and put them into the environment before forking and running
the command.
> extract environment from command_line and set it directly

- debian/control
which is the case for rpms already. And while on it, line up dependencies.
> naemon-core must depend on libnaemon

- lib/runcmd.c
- lib/test-runcmd.c
Commands containing a tilde ~ should be passed to the shell. execvp does not expand it.
> pass commands containing tilde to shell

- tests/test-check-scheduling.c
- tests/test-event-heap.c
While running the tests on Debian, they were failing due to an incompatibility on the size of time_t and the format that was being used when printing the messages in the tests. 
Casting the variables fixed the tests on Debian. After the changes, I ran the tests inside a Ubuntu 20.04 container to make sure they didn't break and everything was fine.
> Cast time_t variables so tests run on Debian

- debian/naemon-core.naemon.init
Sets nonzero exit code status when config test fails.
> configtest_exit_code_fix

- src/naemon/commands.c
- src/naemon/objects_host.c
- src/naemon/objects_service.c
- src/naemon/xrddefault.c
- t-tap/test_commands.c
command crashes because timeperiod is stored with different name.
> fix CHANGE_HOST_CHECK_TIMEPERIOD command

- lib/iobroker.c
- lib/lnae-utils.h
- lib/runcmd.c
Fixing two issues here. If you like separate PRs, just tell me :-)
First one fixes a memory leak in the cmd parser which makes the worker processes grow which
then leads to more cpu usage during all the forking (along with the wasted memory)
The second came to my attention while searching the leak, those two allocations where by far the biggest ones on my test system and both simply depend on the maximum number of open files.
I added a high enough max value to be hopefully future proof without wasting useless memory.
I don't think any naemon worker will ever sanely use more than 100k open file handles. I 
considered adding a log entry or another warning. But at that point, there is no access to the log and stderr/stdout is already closed.
With those patches, memory consumtion seems …
> Fix memory leak in cmd parser

- naemon-core.spec
using an undefined macro trys to run literal %{insserv_cleanup} as shell command which results in the errors like
/var/tmp/rpm-tmp.1P1HM5: line 12: fg: no job control
> rpm: fix fg: no job control

- naemon-core.spec
add a if clause around the systemd-tmpfiles call like we do with all the other systemd calls.
> add if around systemd call

- naemon-core.spec
This commit adds a `BuildRequires` on SUSE to include the systemd macros. This is needed to correctly build on SUSE due to using systemd macros in the specfile.
Signed-off-by: Jacob Hansen <jhansen@itrsgroup.com>
> Spec: Add systemd macros on SUSE

- src/naemon/workers.h
```
naemon/workers.h:15:18: error: ISO C does not allow extra ‘;’ outside of a function [-Werror=pedantic]
```
> fix ISO C does not allow extra ;

- src/naemon/checks_host.c
- src/naemon/checks_service.c
right now all hosts/services have a wrong latency because calculation is based on the integer value of next_check but the scheduled event uses microseconds. So use the latency based on the event timestamp instead which has subsecond precision.
> improve latency handling

- naemon-core.spec
this is a old relict from very early rpms, time to let it go.
```
RPM build warnings:
line 14: It's not recommended to have unversioned Obsoletes: Obsoletes: naemon-tools
```
> fix unversioned obsoletes

- src/naemon/commands.c
add check if fp is not NULL because of:
```
[   92s] In function 'close_command_file',
[   92s]     inlined from 'close_command_file' at src/naemon/commands.c:171:5:
[   92s] src/naemon/commands.c:186:9: error: argument 1 null where non-null expected [-Werror=nonnull]
[   92s]   186 |         fclose(command_file_fp);
[   92s]       |         ^~~~~~~~~~~~~~~~~~~~~~~
[   92s] In file included from src/naemon/objects_host.h:8,
[   92s]                  from src/naemon/comments.h:9,
[   92s]                  from src/naemon/commands.c:3:
[   92s] /usr/include/stdio.h: In function 'close_command_file':
[   92s] /usr/include/stdio.h:183:12: note: in a call to function 'fclose' declared 'nonnull'
[   92s]   183 | extern int fclose (FILE *__stream) __nonnull ((1));
[   92s]       | …
```
> fix Werror=nonnull in close_command_file

- src/naemon/common.h
- src/naemon/macros.c
Previously we used a fixed size 8k buffer when parsing command line arguments. This sounds much, but there are command lines bigger than 8k and they are simply cut off without any warning.
Instead we use a dynamic sized buffer with the size of the raw command now.
(while on it, fixing the crazy indent)
> use dynamic sized command line buffer

- src/naemon/nebmods.c
Print the current and expected api version number along with the error. This gives a hint about wether the neb module is too new or too old.
> be more specific when unloading a neb module

- naemon-core.spec
this (should) fix this build error on obs:
```
[  139s] /.build_patchrpmcheck_scr: line 55: systemd-tmpfiles: command not found
[  139s] postinstall script of naemon-core-1.4.1-lp154.18.1.x86_64.rpm failed
```
> add systemd to build requires

- src/naemon/objects.c
It's a good standard to do so and in fact, we do this already in several places, ex. the status.dat. This ensures the file is ready and completly written before it will be used.
The issue here is, that naemon starts without any issues if the precached file is empty for any reason. Except it has zero hosts/services then and removes all existing states/downtime/comments.
> write objects.precache in tmp file first, then move it

- .vscode/c_cpp_properties.json
- .vscode/launch.json
- naemon-core.spec
- src/naemon/checks_host.c
- src/naemon/common.h
- src/naemon/macros.c
- src/naemon/nebmods.c
- src/naemon/objects.c
- src/naemon/workers.c
While reviewing #419, I noticed that Naemon is not taking care about it's dead worker processes. Whenever a worker process dies, it will become a `<defunct>` zombie process.
The reason for this was, that Naemon did not call `waitpid()` when a worker process dies. I did not find any explanation why this was implemented this way.
Could `waitpid(wp->pid, &i, 0)` hang (wait forever), if the worker process was not forked from the currently running Naemon? We could probably replace this by `waitpid(wp->pid, &i, WNOHANG)`, but I'm not 100% sure about this.
Best I could find about this was: https://github.com/NagiosEnterprises/nagioscore/issues/635
> Fixed: Naemon stops executing checks and doesnt respawn Core Worker #419 

- NEWS
- debian/changelog
- naemon-core.spec
- version.sh
I'd say it's about time for a new releae:
```
1.4.2 - Jan 03 2024
===================
Features:
* remove size limit on external command argument length
* performance improvements when having lots of comments
* respawn dead core worker
Changed:
* write objects.precache into a tmp file first
* increased CURRENT_NEB_API_VERSION to 6 (neb modules need to be rebuild)
Bugfixes:
* fix build error on fedora
* fix latency calculation having negative value sometimes
```
> release 1.4.2

- src/naemon/checks_host.c
- src/naemon/checks_service.c
- src/naemon/notifications.c
Constants like WIFEXITED are defined in sys/wait.h header.
This fixes a compilation issue on FreeBSD where those contants aren't implicitly made available without an explicit include of those.
> Include <sys/wait.h> for wait constants

- src/naemon/workers.h
ETIME alternative implementation as ETIMEDOUT is already available for the worker component, but not for the naemon component.
This fixes the following compilation error on systems without ETIME:
```
src/naemon/workers.c:517:27: error: use of undeclared identifier 'ETIME'
if (wpres.error_code == ETIME) {
^
1 error generated.
```
This has been noticed on FreeBSD.
> Define ETIME for systems without that constant

- src/naemon/notifications.c
This change makes service parents work more like service dependencies. Previously service parents simply dropped all notifications which leads to some issues:
- if a service goes down, sends a notification but comes up before the parent, no recover will be sent
- forced notifications, downtimes etc won't send a notification
With this change only "normal" notifications will be suppressed if all parents are down. But the following notifications will still be sent:
- custom notifications
- acknowlegements
- flapping alerts
- downtime alerts
> suppress only normal notifications from service parents

- lib/nsutils.c
- lib/nsutils.h
- src/naemon/checks_host.c
- src/naemon/checks_service.c
- src/naemon/globals.h
- src/naemon/macros.c
- src/naemon/macros.h
- src/naemon/nebmodules.h
- src/naemon/notifications.c
- src/naemon/objects_host.c
- src/naemon/objects_host.h
- src/naemon/objects_service.c
- src/naemon/objects_service.h
- src/naemon/utils.c
- src/naemon/xrddefault.c
- src/naemon/xsddefault.c
this PR makes hosts / services save the start and end timestamp of the current problem. Those values can then be used as macros, ex. in notification scripts. For this, there are several new macros available:
- `$HOSTPROBLEMSTART$` start timestamp of problem
- `$HOSTPROBLEMEND$` end timestamp of problem (or zero if problem still persists)
- `$HOSTPROBLEMDURATIONSEC$` duration of problem
- `$HOSTPROBLEMDURATION$` duration as human readable text
the same macros exist for services:
- `$SERVICEPROBLEMSTART$`
- `$SERVICEPROBLEMEND$`
- `$SERVICEPROBLEMDURATIONSEC$`
- `$SERVICEPROBLEMDURATION$`
While there is a currently ongoing problem, the values point to this current problem and the end timestamp is zero. Once the problem is resolved, the values can still be used and won't change until a new …
> add problem timestamps and duration

- src/naemon/xrddefault.c
resetting modified_attributes to zero had no effect. The reason was a wrong assumption when reading the retention file. The retained value was restored even if the correspondig modified_attributes was not set (anymore).
Now we have the following attribute changes (assuming retention is enabled):
- attribute was changed via gui -> retained on next reload
- attribute was changed via gui but config value changed afterwards -> use the configured value instead of the retained one
- config value changed and attribute has not been changed via gui -> use the configured value
> fix resetting modified_attributes

- src/naemon/commands.c
all commands update the last_update attribute, so do this for CHANGE_CUSTOM_*_VAR commands as well.
> fix updating last_update when sending CHANGE_CUSTOM_*_VAR command

- src/naemon/notifications.c
if global enable_flap_detection has been disabled but hosts/services still have the is_flapping flag set, notifications will be held back forever.
the quick fix is to ignore the flapping state if its disabled globally.
- #434
> check global enable_flap_detection flag for notifications

- src/naemon/checks_host.c
Currently the hosts last_state_change and last_hard_state_change will only be initialized if the state changes or in check_service.c when the first service result arives. I see no reason why this shouldn't be done for host results as well.
> initialize hosts last_state_change and last_hard_state_change

- src/naemon/events.c
there is no reason to have 2 entries in the debug log for the same execution path. And i always found this entry confusing.
> remove duplicate log entry

- naemon-core.spec
The posttrans scriptlet executes after the RPM transaction has concluded, i.e. when all packages have been installed or upgraded. Delaying the Naemon restart until posttrans prevents API compatibility issues when naemon-core upgrades before naemon-livestatus. See https://github.com/naemon/naemon-core/issues/454.
Note that it is not possible to infer the RPM operation (install or upgrade) from the posttrans scriptlet argument, since they are the same: https://en.opensuse.org/openSUSE:Packaging_scriptlet_snippets#Syntax This should not cause any problems since the scriptlet only restarts Naemon if it was already running. In other words, it won't cause Naemon to start immediately after installation.
> fix(rpm): Delay Naemon restart until posttrans

- src/naemon/checks_host.c
- src/naemon/checks_service.c
there were some corner cases where the last_update timestamp has not been updated. Update the timestamp whenever the last_check changes.
> update last_update for some more cornercases

- sample-config/naemon.cfg.in
- src/naemon/checks_host.c
- src/naemon/checks_service.c
- src/naemon/configuration.c
- src/naemon/defaults.h
- src/naemon/globals.h
- src/naemon/utils.c
The issue with the options:
- host_down_disable_service_checks
- service_skip_check_dependency_status
- service_skip_check_host_down_status
- host_skip_check_dependency_status
is that reports break because hosts/services suddenly stop executing and
keep their OK state. Which makes those options pretty unusable.
So in order to keep reporting correct, you need to keep services running, even
if the host is down. With these new options, hosts/services keep on running as
long as they are up. And as soon as the service is down, it stops running until
the host comes back up. That way naemon has to do less checks, especially less
checks which run into timeouts and such but reporting is still correct.
The option service_skip_check_dependency_status=-2 will also be used for service parents.
Adding …
> add new options to keep services running as long as they are ok

- src/naemon/comments.c
This pull request is to remove the nullifying of service comment list prior the removal of the comment from the list.
> Remove nullifying of service comment list before removal of a comment

- src/naemon/checks_host.c
a host should directly change into a hard state when max_check_attempts=1 is set and the host goes down.
> fix host not being in hard state with max_check_attempts=1 (fixes #473)

- src/naemon/xodtemplate.c
whenever naemon encounters a 'Error: Duplicate definition found for' it will now print the location of the previous object definition as well to make debugging easier.
While on it, rework xodtemplate_add_object_property() a bit and clean up code. Instead of setting a result, simply return early with the error. There is no cleanup at the end or something like that. Also cleanup the double use of the result variable which was used for the result but also for determing if there is a value set or not.
> add hint of previous object when duplicate detection fails

- .vscode/launch.json
Add setupCommand example to default launch.json to demonstrate how to set gdb options.
The example set an option to ignore SIGPIPE
> Update launch.json with an example how to pass options to gdb

- src/naemon/naemon.c
only print the requested information.
when running with -V simply print the version and exit.
when running with -h only print help and exit
when running with -L only print license and exit
> cleanup output

- src/naemon/objects.c
using fopen opens the object.cache a second time and naemon closes just one afterwards. So with every write of the objects.cache file, one reference will be kept and prevents the file from beeing deleted which finally fills the disk with deleted files. Using fdopen solves the issue, since it just reuses the existing fd.
> fix leaking object.cache file references (fixes #462)

- NEWS
- debian/changelog
- naemon-core.spec
- version.sh
1.4.3 - Nov 19 2024
===================
Features:
* add global notifications handler (#477)
* add external command to add log entries (#477)
* add hint of previous object when duplicate detection fails (#479)
* add options to keep services running as long as they are up (#459)
* add problem timestamps and duration (#447)
Changed:
* clean up output of naemon -V (#484)
* change problem_id and notification_id to uuids (#362)
* change service parents suppressing only normal notifcations (#446)
Bugfixes:
* fix leaking object.cache file references (#462)
* fix host not being in hard state with max_check_attempts=1 (#473)
* throw config errors if boolean values cannot be parsed (#478)
* fix retrieving comments after deleting first (#474)
* fix rpm installation race condition (#456)
* fix …
> Release 1 4 3

- src/naemon/checks_host.c
- src/naemon/checks_host.h
- src/naemon/checks_service.c
- src/naemon/checks_service.h
- src/naemon/objects_timeperiod.c
Given a service with a 24h check interval and a office hours check period. If this service is scheduled for whatever reasons outside office hours, it will be rescheduled 24hours again which is also outside office hours.
In the end, this service will never be checked again.
So, when naemon detects a check which could not be run because it is outside the check period, postpone the check until the next slot in its check period.
> postpone check until check period starts

- .github/workflows/citest.yml
- .github/workflows/codeql.yml
this PR updates the github actions to ubuntu 24.04 since 20.04 is end of life soon.
> github: change github actions to ubuntu 24.04

- src/naemon/naemon.c
- src/naemon/shared.c
- src/naemon/shared.h
- src/naemon/xodtemplate.c
- src/naemon/xrddefault.c
- use faster trim method
- skip sanitizing dependencies when reading precached objects
- skip regexp matching when reading precached objects
> improve config parser performance

- sample-config/naemon.cfg.in
- src/naemon/common.h
- src/naemon/configuration.c
- src/naemon/naemon.c
- src/naemon/shared.c
- t-tap/test_commands.c
- t-tap/test_config.c
- t-tap/test_timeperiods.c
- tests/test-config.c
Naemon already supports relative include paths and uses the folder of the main naemon.cfg as base path.
This is fine unless you want to generate the main naemon.cfg and start naemon from a tmp folder. In this case, i'd like to set the base path from the config file.
By default nothing changes, but you can now override this by setting `config_rel_path`.
> add support for configurable relative configuration paths

- src/naemon/checks.c
- src/naemon/xodtemplate.c
Fixing 2 small issues.
- remove trailing white space in check results.
- remove backslashes used to escape semicolons.
> Fix 2 small issues

- src/naemon/checks.c
- src/naemon/checks.h
- src/naemon/checks_host.c
- src/naemon/checks_host.h
- src/naemon/checks_service.c
- src/naemon/checks_service.h
- src/naemon/objects_timeperiod.c
- src/naemon/objects_timeperiod.h
- src/naemon/shared.c
- src/naemon/shared.h
- t-tap/test_timeperiods.c
with #490 we rescheduled checks found outside their check period to the next time slot in their check period with a random delay of 60 seconds (or what ever retained_scheduling_randomize_window was set to)
There are 2 scenarios when this leads to scheduling issues:
1) Lots of checks with a medium check interval (ex. 2h) and office hours
timeperiod. Those checks should evenly be scheduled over the 2h interval
but currently, they would start with the office hours and from then they
all at once every 2 hours which results in load peaks.
The solution here is to take the check period into account when postponing
the next check.
2) Consider checks with a long check interval (ex.: 24h) and small timeperiods,
ex.: only 08:00 till 08:05. In this case we need to take the actual time slot
into …
> improve postpone checks outside of check period

- src/naemon/checks.c
apparently the check output can be null, which makes the rstrip crash. So better check this first.
> fix crash in check post processing

- src/naemon/objects_common.c
- tests.mk
- tests/configs/tabs/host.cfg
- tests/configs/tabs/naemon.cfg
- tests/configs/umlauts/host.cfg
- tests/configs/umlauts/naemon.cfg
- tests/test-config.c
It is a bad idea to create objects containing newlines or tabs but it's not that easy to add those characters to the illegal_object_name_chars list. So make them illegal by default.
> make ascii control characters in object names illegal

- features/steps/naemon.py
- src/naemon/commands.c
- src/naemon/naemon.c
- src/naemon/query-handler.c
- src/naemon/query-handler.h
- src/naemon/utils.c
- src/naemon/utils.h
since the command worker forks from the main naemon process, it inherits all open files like ex.: pidfile, logfiles, etc... It will keep those references open, even if the main process rotates and reopens those files.
This patch closes query handler and pid file references after starting the command worker and also moves starting the command worker before initializing the neb modules, so it won't inherit open logfiles from neb modules.
references:
- https://github.com/ConSol-Monitoring/omd/issues/146
> launch command worker earlier

- src/naemon/xrddefault.c
During the startup of Naemon, Naemon will first load retention data from the `retention.dat` file by calling `read_initial_state_information()`
While Naemon is processing the host and service information from the `retention.dat`, Naemon will call `update_host_status()` and `update_service_status()`.
At this point in time, Naemon has NOT loaded the downtimes from the `retention.dat` file - so the value of `scheduled_downtime_depth` is `0`.
A few nanoseconds later, Naemon will call `checks_init()`, which will call `update_host_status()` and `update_service_status()` for all hosts and services again, but this time with the correct value for `scheduled_downtime_depth`.
Instead of calling the broker modules while we are restoring the previous state from the `retation.dat`, we will now call the …
> Remove update of host and service status during the restore from retention.dat
